language: node_js
node_js:
  - 16

addons:
  sonarcloud:
    organization: "sylk80"
    token:
      secure: "NxXxsrqMKaXSRXe4/32XeGQ5cyQwgGt8HhCPtihMIlEqfM5/unUjbuvGXpDCLm8mnhrzlwn5j1XFH1lrq9q52g61SPi4AQe6JPsmf1zWzGuY0LQubvx0IHxNFgCnSzG+NuWzQ9M/jdAl4CL4UvDWaOqoj+p08q7+NLIAkQqXgL6W8Ht8RV5mJDaE1FmhTNmDoN0GO331HgZwymzAaYOBUJ2p6O2i2ac2g0H9o1524PITXHH7fFPtGXxr0X6evnEobLDpe8Ze6WS7gQlzxFviM6r8A1Vkzap7XGZInpqtGxUyyIvBVVApd3LHy4kvOfFWb7AEsbUoYge2lzeDj/AV9iCZJTmDxnOJK79ieCOuAXMxqgifxwfr31LBykUoHlj29pYPNLUdivu2SnvX+rg0ATueAPBnv6+SmzmVSjLm+fqYjMPe0swyM7z3knC6RZS3Ju2Hq2uAD9Ke2zWkxcaytOIDgyiMSH3Dgo91lmYYA2EhAokf8nsiMYhiPVcsaNUdqdYJXj8CmyZPghuorBeWcQx1hDKq8k35CJ29ny9rwAJmdYzfgt+DO7eEL1mI5VCCXa4cMFDrDyXwMpPaI7JsZfnLozahgTrbc1++hJDc9MrpEse8mZO3EwvocxuvTudV1fZoUqOCIbanSCOvWNu0lOBytOQQ8JmqJ5Kf96hTeus="

env:
  global:
    secure: "ortPDZXBGXzCClHRdmov9KHt8pKLBl8eFNFZ5PdJGqRqksBRDlvQUBfxm7ZexqYuH+mMyt/BuwD6x/Bnai1NYrQzdUQJT5N+8/lmZY/HyuKNWS7HjggG231upR2+S1/Xl82G7biee2wE5ryHRMt2U019o/UFz6OkIcm5Rreitvz+00HdoDSENgan8zvcI6SIGtE1j1swpo3M3IoUq0A8g7QvxClsWU8vgoccScsXDi6usY02GUi7HATWFw1NsRqq5y8lDMzRnHn/tPGmr929LVHZQKzNuabj9Q2cMwteLw8ViMv58t4ZyWl93+ga9NswId3c41yatl18UE1eG607WTDKEyKhYqvd/tAaAp2ztk1+9zVinaKrpHxG7bHrLF8Q2HRtDlTTVhkaSYUTfgHkId0i8nIn+Aq5S3ZitmDhSGQ4ycWb7YwqqNVR9qNSoTeXV8MVCciGxOCAxTIeBz2b2imZgh5q17exXybBo+031kOynkeqhQt6cwkx8XIXyHGAgg+WY2kCUgw1udKnUK4nIsrXN3VHckN92G8cDHBAppKv3uozI3izfmCb3ZojlXj8SR+egV9NevL76//vl6AzMmVyjkwk5q0QFUpZGgHh8mMXeJr3Ejab/p5+CYX1g4b/b9ilfo5pr/bYL4imkpdVSEYpQC/iWwuPY4enAXEO5RE="



before_install:
  - npm i -g npm@8.3.1
  - npm install -g snyk@latest
  - snyk -v
stages:
  - name: Build
  - name: Test
  - name: Deploy
jobs:
  include:
  - stage: Build
  - env: step=Run Snyk vulnerability check
    name: Run Snyk vulnerability check
    script:
      - snyk auth
      - snyk test
  - env: step=Run linter
    name: Run linter
    script:
      - npm run lint
  - stage: Test
  - env: step=Run unit tests
    name: Run unit test
    script:
      - npm test
  - env: step=Run Sonar Scanner
    name: Run Sonar Scanner
    script:
     - sonar-scanner
  - stage: Deploy
    env: step=Deploy to Firebase
    name: Deploy to Firebase
    provider: firebase
    token:
      secure: "QdUX0eXvWtu5ex+Ajdwbz/fNIpcZM0kDJskvx/ZotorjzvAfOKXz5T5XK9kP2tfMpOQ15Oecd4248WTIY7u7LGfJXU8P8em0hEPA+JlwgI9NLLSAz8JBvWLK2VlLc7cDzthgsX8Tq/8XNu8zMIlhxgNLDXqegR7WI7SiW4E6FLjYMgk2HRQ5k4nngDNAxXkUQ/AFqecPSIaGlZWMSJo8PqG5YcrkAYSp0+i+josqqNkEtVRDxS6RVPpU3oY1RM0afqN6e2/5ArnjeMnETPmusx8Nsqeou+pXfpxcB+wYKZU6p7FO59SlPoG06K83Z9OWDLMp3WRJi88ZoBV+xpHZdFAIJSH8eiEQypeUFYkKWZOveISBHi5I2T+XzBX+HwWONB9lB11sVWDIJeH7fmcFbz3u7Re9rM42ujqSu2iVJOaSHZMnnantutVYfLbMn+ua1G0juZKrq+XTg9UXVf6MQKiB9Y0GPAdWd68D3LgM/U0B3/YSswuFbCO70xx2clyngFPzSZItJYWXwA9gSppeZfKKMXAIHDF4QQohTsFtl7RA1gz1uwQThhf02Ax0yk89wAcSeWoIc5zUCmLBT7asRDgx6+6p9FmJeqXwKPhHj7PPuu+Otj6ECCj3rCyEKG/sYAdjDFJ0rDn/xAe5M8EL0s/wAweOaNcf1fqsMLQ9rTg="
      project: "xpfarm-test"