language: node_js
node_js:
  - 16

addons:
  sonarcloud:
    organization: "sylk80"
    token:
      secure: "PM9C+MFdn+JB2wP5oR0ku0QZ7hrHKN1ZuxAO4zzV1CkbsnZoZKnIVToo2NxyUMqGrLExNAuSMjZSjnJ7FPpOfIZM08O+XwpDjOUWFKsKKOdFcBqPRPLV53HZA7c0NCWEdXcJjd6tcnyEiPYgPtSgkSRaDYyH1Od/u4iRwQMdJL7BkB0jUDnOGcCxkObzFOkYtokY6OYqxEdE0tIjYVRk+wZKY4vIjJVyecCc8+nOlc0xR0Dx4OknJ7waUiJLSehqfKCokmQhp7fIKTsp5sabj7yCU9DlcZ/QstzI9xtiD9ESOzt7e0A18xf0j/ssFNyGa2i06rOOJ0+3bjboqhvwMsPTBxM9nK0LRCFiyXAi7BLd21Ct245B5rcHMIdvBnqvQyb6Lv3O1AiEApFHzBnyOfBCTyoXYmGTEPYj+q2F0OIqpysfGFI3COb5RC+Ug1lqi4TpUw1L/JehCbiYNFgQDXA092rQM9zstYe+QrVZfA2tKzBAq7M4L0kBswl3WlF3CwYBkVW1dU9GD3JGWq7T2rcj1kb/9Mf4FD6zpFjW/Jhpg7aZxYWkhIwWce55bz3d3qYEA6lm/5nn5D5RxWENZi0lBVzuVY/Qw4W8n1Ba57CpJ71jQYOz8bv86k5hyl+Bg40n3WkJqHdtLhweJJHSm4gZ9yr7K9CCue/dCpI5G1s="

env:
  global:
    secure: "Q9o4MeZPwu1TfvIodiehiq+EILTngIhjgb4fbrXmRCUF306RpMrjI1v/PH1qIbYzxxBtnfzE+CUiSpGF7Vr2CntgIf6gNKiZdg9RsU9AcQZXliEQoH0/a89HQ3VsDtCwr7nnTEw5Q1N69x9M377XT44iiAZoNa+aQkcyxTOw+gHlaBViW6FNkJS6+NJ0xL5NZlolFlnIGHPVEq0L+3fkUEsfB7CwL7vfZvmEktOvJ1sXYAo6PBLjDpzY7mDKlj6wysQ4cjtJGBWahiexdJOzfbmYp0KuioWxtGv8WGuy9PWV4eCvU2RBmkPI0M1t7C6GToS/NKs104atafHDN/lSgcybxLdTOHP8+hBqSu64CHRqMZ/CNN2fu8FuuDnIwA1/vU01X7I6ghBDEP3FsIX7vDEv2B7OwuyAER9YWwIg3F8vfJ5C2spR5gz2UsVAhr/1+2GNcwpSyydyaOuJAPSTC2I07A0G+Ipux9CGpJKLU3FqdmagNl27vjJxPG/jVCU6DcButCf3bHO5GuC3FxJ8VhVxSw1GWaErixlGV91B0D//jdyszp0T+CqhEhshwYbry23oPqtvoyAry9EoARuFAA1FLvbeZHTwuFJLssCFOJxAlJiwJQ/SE0AO+D32fpkYKOM9WmwcQPBnLHtdSo4peKg9TXcIKkkCClcqnvb6aAc="

before_install:
  - npm i -g npm@8.3.1
stages:
  - name: Test
  - name: Deploy
jobs:
  include:
  - stage: Test
  - env: step=Run unit tests
    name: Run unit test
    script:
      - npm test
  - env: step= Run Snyk vulnerability check
    name: Run Snyk vulnerability check
    script:
      - snyk test
  - env: step= Run Sonar Scanner
    name: Run Sonar Scanner
    script:
     - sonar-scanner
  - env: step=Run linter
    name: Run linter
    script:
     - npm run lint
  - stage: Deploy
    env: step=Deploy to Firebase
    name=Deploy to Firebase
    provider: firebase
    token:
      secure: "QdUX0eXvWtu5ex+Ajdwbz/fNIpcZM0kDJskvx/ZotorjzvAfOKXz5T5XK9kP2tfMpOQ15Oecd4248WTIY7u7LGfJXU8P8em0hEPA+JlwgI9NLLSAz8JBvWLK2VlLc7cDzthgsX8Tq/8XNu8zMIlhxgNLDXqegR7WI7SiW4E6FLjYMgk2HRQ5k4nngDNAxXkUQ/AFqecPSIaGlZWMSJo8PqG5YcrkAYSp0+i+josqqNkEtVRDxS6RVPpU3oY1RM0afqN6e2/5ArnjeMnETPmusx8Nsqeou+pXfpxcB+wYKZU6p7FO59SlPoG06K83Z9OWDLMp3WRJi88ZoBV+xpHZdFAIJSH8eiEQypeUFYkKWZOveISBHi5I2T+XzBX+HwWONB9lB11sVWDIJeH7fmcFbz3u7Re9rM42ujqSu2iVJOaSHZMnnantutVYfLbMn+ua1G0juZKrq+XTg9UXVf6MQKiB9Y0GPAdWd68D3LgM/U0B3/YSswuFbCO70xx2clyngFPzSZItJYWXwA9gSppeZfKKMXAIHDF4QQohTsFtl7RA1gz1uwQThhf02Ax0yk89wAcSeWoIc5zUCmLBT7asRDgx6+6p9FmJeqXwKPhHj7PPuu+Otj6ECCj3rCyEKG/sYAdjDFJ0rDn/xAe5M8EL0s/wAweOaNcf1fqsMLQ9rTg="
      project: "xpfarm-test"